#part 1
def grid():
    border_row = (('+ ') + ('- ' * 4)) * 2 + ('+')
    border_column = (('| ') + (' ' * 8)) * 2 + ('|')
    print(border_row)
    print()
    print(border_column)
    print()
    print(border_column)
    print()
    print(border_column)
    print()
    print(border_column)
    print()
    print(border_row)
    print()
    print(border_column)
    print()
    print(border_column)
    print()
    print(border_column)
    print()
    print(border_column)
    print()
    print(border_row)    
