#!/usr/bin/env python3

import os

###    Part 1 - print the files in the active directory....

#Get the path of the current working directory - that is - the directory that this file is stored in...
current_working_directory = os.path.abspath(os.getcwd())
#Get the files in the current working directory as a list...
files = os.listdir(current_working_directory)
#Iterate the list, build the full path and file name and print...
for file in files:
    print(os.path.join(current_working_directory, file))
    


###part 2 copy file without os or shutil....
    
#I get that is is tidy but not so readable for me (I am a dullard) so I wrote it (below)like I would if I needed to use it...
#with open(in_file, "rb") as in_f, open(out_file, "wb") as out_f:
    #read = in_f.read()
    #out_f.write(read)

#Open an file and read as a binary file...
in_f = open(in_file,'rb')
#Open a file to write binary...
out_f = open(out_file, 'wb')
#Read the file into memory...
read_file = in_f.read()
#Write the file...
out_f.write(read_file)
out_f.close()	

###part 3 - make a set of languages....
in_file = 'students.txt'
#Open file...
in_file = open(in_file)
#Make an empty set to hold the languages...
languages = set()
#make a dictionary to hold names and language counts...
lang_by_coder = {}
#To skip the first row...
row_count = 0
for line in in_file:
    #Skip the file header...
    if row_count == 0:
        row_count = 1
        pass
    else:
        #Seporate names from languages by splitting at :, strip off the pesky escape characters, and split the list on commas...
        codes = line.split(':')[1].rstrip("\n").split(',')
        #Get coder name...
        coder = line.split(':')[0]
        lang_count = 0
        for i in codes:
            #Strip off the leading and tailing blank spaces...
            i = i.strip()
            #Only add the lower case items to the set...
            if i.islower():
                #Add one to the language count...
                lang_count +=1
                #Add language to the set...
                languages.add(i)
        #Create a new dictionary item with the language count...
        lang_by_coder[coder] = lang_count
print(languages)
print(lang_by_coder)


